# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tarefa.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tarefa.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctarefa.proto\"\x1b\n\rTarefaRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"O\n\x0bTarefaReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\x11\n\tconcluida\x18\x04 \x01(\x08\x32<\n\rTarefaService\x12+\n\x0bObterTarefa\x12\x0e.TarefaRequest\x1a\x0c.TarefaReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tarefa_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAREFAREQUEST']._serialized_start=16
  _globals['_TAREFAREQUEST']._serialized_end=43
  _globals['_TAREFAREPLY']._serialized_start=45
  _globals['_TAREFAREPLY']._serialized_end=124
  _globals['_TAREFASERVICE']._serialized_start=126
  _globals['_TAREFASERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
